### PR TITLE
added osgi support

### PR DESCRIPTION
**Pull request by rburgst**
- in order to be able to use license3j for OSGi valid import and
  export statements need to be provided.
- note that we are using bundle plugin 2.3.7 on purpose as newer
  versions (e.g. 2.5.3) would not allow to have the License3j.java
  in the root package (and I was too lazy to figure out how to make
  it work)

### CODE REVIEW

**Comment by rburgst** [comment]
I am confused, the artifacts available on the website and in mvn repository dont have the OSGi headers.

**Comment by verhas** [comment]
I am not familiar with OSGi, I have never used it. However I tried to use the modified `pom.xml` and here are my concerns:

- The created manifest file does not specify the main class any more.
- The compilation gives a warnings

```
[WARNING] Bundle com.verhas:license3j:bundle:1.0.6-SNAPSHOT : Instructions in Private-Package, or -testpackages that are never used: \.
Classpath: Jar:.,Jar:bcpg-jdk15on,Jar:bcprov-jdk15on
[WARNING] Bundle com.verhas:license3j:bundle:1.0.6-SNAPSHOT : Did not find matching referal for !.
```

**Comment by medisite** [comment]
excerpt from my pom:

<dependencies>
  ...  
  <dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcpg-jdk15on</artifactId>
    <version>1.51</version>
  </dependency>
  <dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.51</version>
  </dependency>

  <dependency>
    <groupId>com.verhas</groupId>
    <artifactId>license3j</artifactId>
    <version>1.0.5</version>
  </dependency>
  ...
</dependencies>
...
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.felix</groupId>
      <artifactId>maven-bundle-plugin</artifactId>
      <configuration>
        <instructions>
          ...
          <Embed-Dependency>						
            license3j;inline=com/verhas/licensor/**,
            license3j;inline=com/verhas/utils/**										
          </Embed-Dependency>
		  ...          
        </instructions>
      </configuration>
    </plugin>
	...
  </plugins>
</build>
...

**Comment by medisite** [comment]
you must have a dependency to licence3j artifact, then you need to have 'Embed-Dependency' tag to declare what do you have to embed in your artifact. The following lines embed the classes from license3j to your bundle:

license3j;inline=com/verhas/licensor/**,
license3j;inline=com/verhas/utils/**

The 'Embed-Dependency' tag is part of 'instructions' and 'configuration' of maven-bundle-plugin

**Comment by medisite** [comment]
Ah sorry, i understood! 
You will make the license3j OSGi campatible.

This is also what i have to do ;)

Sorry for confusing - i thought you will use license3j(non OSGi) in OSGi environment.

**Comment by medisite** [comment]
Its very simple to make the license3j artifact compatible to OSGi.
The resolution is to move the License3j class to new package like com.verhas.sample

Don't forget to modify the documemtation to make it possible to run License3j class from command line. 

Thats all.

**Pull request closed without merging**
